#!/bin/sh
echo "Remvoing Old Two Toasters Templates"
rm -rf ~/Library/Developer/Xcode/Templates/Two\ Toasters
echo "Installing new Two Toasters Templates"
mkdir -p ~/Library/Developer/Xcode/Templates/Two\ Toasters
cp -r Project\ Templates/* ~/Library/Developer/Xcode/Templates/Two\ Toasters/
# cp -r File\ Templates/* ~/Library/Application\ Support/Developer/Shared/Xcode/File\ Templates/Two\ Toasters
echo "Done"